# This is a template. Read README-Crosschain.md

#data-path="."
#genesis-file="../genesis.json"

#logging="DEBUG"
min-gas-price="0"
miner-extra-data="This is just a template! Read the README-Crosschains.md"

p2p-enabled=false
rpc-http-enabled=true
rpc-http-api=["ETH","NET","WEB3","CC"]
rpc-http-port="This is just a template! Read the README-Crosschains.md"

crosschain-enabled=true
crosschain-config="crosschain/resources/crosschain.config"
