# Copyright 2018 ConsenSys AG.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

# Project information
site_name: Pantheon
site_url: https://docs.pantheon.pegasys.tech/
site_description: Pantheon Java Ethereum client documentation.
site_author: Pantheon community
copyright: Pantheon and its documentation are licensed under Apache 2.0 license /
  This <a href="https://readthedocs.org/">Readthedocs.org</a> documentation is maintained with love by <a href="https://pegasys.tech/">PegaSys</a>.

#extra project info and template customisation
extra:
  support:
    gitter: https://gitter.im/PegaSysEng/pantheon
    email: support@pegasys.tech
  google:
    analytics_id: 'UA-117921923-2'
    site_verification: 'za1cLzyS6LXDGO-pMzvfQdYTZ0Zc67uZtY0asA4YXZ0'


# Repository
repo_name: PegaSysEng/pantheon
repo_url: https://github.com/PegaSysEng/pantheon
edit_uri: ""

theme:
    name: material
    custom_dir: docs/custom_theme
    palette:
        primary: blue-grey
        accent: teal
    favicon: favicon.ico
    logo:
      icon: account_balance
nav:
    - Installation:
        - Installation Overview: Installation/Overview.md
        - Install Binary Distribution: Installation/Install-Binaries.md
        - Build from Source: Installation/Build-From-Source.md
    - Getting Started:
        - Getting Started Overview: Getting-Started/Getting-Started.md
        - Starting Pantheon: Getting-Started/Starting-Pantheon.md
        - Running Pantheon from Docker Image: Getting-Started/Run-Docker-Image.md
    - Tutorials:
        - Private Network Quickstart: Tutorials/Private-Network-Quickstart.md
        - Create a Private Network using Ethash (Pow): Tutorials/Create-Private-Network.md
        - Create a Private Network using Clique (PoA): Tutorials/Create-Private-Clique-Network.md
        - Create a Private Network using IBFT 2.0 (PoA): Tutorials/Create-IBFT-Network.md
        - Create a Permissioned Network: Tutorials/Create-Permissioned-Network.md
    - Consensus Protocols:
        - Pantheon Consensus Protocols: Consensus-Protocols/Overview-Consensus.md
        - Comparing PoA Consensus Protocols: Consensus-Protocols/Comparing-PoA.md
        - Clique: Consensus-Protocols/Clique.md
        - IBFT 2.0: Consensus-Protocols/IBFT.md
    - JSON-RPC API:
        - Overview: JSON-RPC-API/JSON-RPC-API.md
        - Using the JSON-RPC API: JSON-RPC-API/Using-JSON-RPC-API.md
        - Authentication: JSON-RPC-API/Authentication.md
    - Configuring Pantheon:
        - Configuration File: Configuring-Pantheon/Using-Configuration-File.md
        - Network ID and Chain ID: Configuring-Pantheon/NetworkID-And-ChainID.md
        - Contracts in Genesis: Configuring-Pantheon/Contracts-in-Genesis.md
        - Node Keys: Configuring-Pantheon/Node-Keys.md
        - Networking: Configuring-Pantheon/Networking.md
        - Accounts for Testing: Configuring-Pantheon/Accounts-for-Testing.md
        - Logging: Configuring-Pantheon/Logging.md
        - Bootnodes: Configuring-Pantheon/Bootnodes.md
        - Passing JVM Options: Configuring-Pantheon/Passing-JVM-Options.md
    - Permissions:
        - Nodes and Accounts Whitelists: Permissions/Permissioning.md
    - Using Pantheon:
        - Events and Logs:
          - Overview: Using-Pantheon/Events-and-Logs.md
          - Accessing Logs Using JSON-RPC API: Using-Pantheon/Accessing-Logs-Using-JSON-RPC.md
        - Creating and Sending Transactions: Using-Pantheon/Transactions.md
        - Using Wallets for Account Management: Using-Pantheon/Account-Management.md
        - Mining: Using-Pantheon/Mining.md
        - RPC Pub/Sub: Using-Pantheon/RPC-PubSub.md
        - Debugging Pantheon: Using-Pantheon/Debugging.md
    - Reference:
        - Pantheon Command Line: Reference/Pantheon-CLI-Syntax.md
        - JSON-RPC API Methods: Reference/JSON-RPC-API-Methods.md
        - JSON-RPC API Objects: Reference/JSON-RPC-API-Objects.md
    - Resources:
        - Blog Posts and Webinars: Resources/Resources.md

markdown_extensions:
    - toc:
        permalink: ÔÉÅ
        toc_depth: 3
    - pymdownx.highlight:
    - markdown_include.include:
        base_path: docs
    - admonition
    - footnotes
    - def_list
    - abbr
    - pymdownx.arithmatex
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde
    - meta
    - smarty

plugins:
    - search
