version: '2.2'
services:
  bootnode:
    build:
      context: ../
      dockerfile: quickstart/pantheon/Dockerfile
    image: quickstart/pantheon:latest
    entrypoint: /opt/pantheon/bootnode_start.sh --dev-mode
    volumes:
      - public-keys:/opt/pantheon/public-keys
  minernode:
    image: quickstart/pantheon:latest
#  The address 0xfe3b557e8fb62b89f4916b721be55ceb828dbd73 is one of the addresses in the
#  dev mode genesys file
    command: ["--dev-mode",
              "--miner-enabled",
              "--miner-coinbase=0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"]
    volumes:
      - public-keys:/opt/pantheon/public-keys
    depends_on:
      - bootnode
  node:
    image: quickstart/pantheon:latest
    command: ["--dev-mode"]
    volumes:
      - public-keys:/opt/pantheon/public-keys
    depends_on:
      - bootnode
  rpcnode:
    image: quickstart/pantheon:latest
    command: ["--dev-mode",
              "--rpc-enabled",
              "--rpc-listen=0.0.0.0:8545",
              "--ws-enabled",
              "--ws-listen=0.0.0.0:8546",
              "--rpc-cors-origins=*"]
    volumes:
      - public-keys:/opt/pantheon/public-keys
    depends_on:
      - bootnode
    ports:
      - "8545"
      - "8546"
  explorer:
    build:
      context: explorer
    image: ethereum-explorer:latest
    depends_on:
      - rpcnode
    ports:
      - "3000"
volumes:
  public-keys: