name: bft-soak-test
on:
  workflow_dispatch:
    inputs:
      consensus-type:
        description: 'Consensus type to test'
        required: false
        default: 'qbft'
        type: choice
        options:
          - all
          - qbft
          - ibft2
      soak-time-mins:
        description: 'Duration of soak test in minutes (minimum 60)'
        required: false
        default: '60'
        type: string

env:
  GRADLE_OPTS: "-Xmx6g -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true"

jobs:
  bft-soak-test:
    name: "BFT Soak Test (${{ inputs.consensus-type }})"
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    permissions:
      statuses: write
      checks: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ github.ref }}
      - name: Set up Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00
        with:
          distribution: temurin
          java-version: 21
      - name: setup gradle
        uses: gradle/actions/setup-gradle@9e899d11ad247ec76be7a60bc1cf9d3abbb9e7f1
        with:
          cache-disabled: true
      - name: run BFT soak test
        run: ./gradlew :acceptance-tests:tests:acceptanceTestBftSoak -Dacctests.soakTimeMins=${{ inputs['soak-time-mins'] }} -Dacctests.consensusType=${{ inputs.consensus-type }}
      - name: Upload BFT Soak Test HTML Reports
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
        if: always()
        with:
          name: bft-soak-test-html-reports-${{ inputs.consensus-type }}
          path: 'acceptance-tests/tests/build/reports/tests/**'
      - name: Upload BFT Soak Test Results
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
        if: always()
        with:
          name: bft-soak-test-results-${{ inputs.consensus-type }}
          path: 'acceptance-tests/tests/build/test-results/**/TEST-*.xml'
