name: nightly
on:
  schedule:
    - cron: '0 5 * * *' # run at 5 AM UTC

env:
  GRADLE_OPTS: "-Xmx4g -Dorg.gradle.daemon=false"

jobs:
  run-acceptance-tests:
    runs-on: [self-hosted, Linux, X64]
    timeout-minutes: 90
    name: "Run acceptance test suite"
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
          cache: gradle
      - name: Cache classes
        uses: actions/cache@v3
        with:
          path: "**/*.class"
          key: ${{ runner.os }}-build-${{ github.sha }}
      - name: ethereum acceptance tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: acceptanceTest --scan
      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        if: always() # always run even if the previous step fails
        with:
          name: junit-acceptance-test-results
          path: '**/build/test-results/acceptanceTest/TEST-*.xml'
          retention-days: 1
